import { test } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { config } from '../config/index.js';
import { signOfflinePayload, getPublicKeySpkiBase64 } from './offlineLicenseCrypto.js';

function verifyWithNode(payloadString, signatureBase64, publicKeySpkiBase64) {
  const publicKey = crypto.createPublicKey({
    key: Buffer.from(publicKeySpkiBase64, 'base64'),
    format: 'der',
    type: 'spki',
  });
  return crypto.verify(
    'sha256',
    Buffer.from(payloadString, 'utf8'),
    { key: publicKey, dsaEncoding: 'ieee-p1363' },
    Buffer.from(signatureBase64, 'base64'),
  );
}

test('a signed payload verifies successfully against the exported public key', () => {
  const payload = JSON.stringify({ restaurantId: 'r1', offlineExpiration: '2030-01-01T00:00:00.000Z' });
  const signature = signOfflinePayload(payload);
  const publicKey = getPublicKeySpkiBase64();
  assert.equal(verifyWithNode(payload, signature, publicKey), true);
});

test('tampering with the payload after signing invalidates the signature', () => {
  const payload = JSON.stringify({ restaurantId: 'r1', offlineExpiration: '2030-01-01T00:00:00.000Z' });
  const signature = signOfflinePayload(payload);
  const publicKey = getPublicKeySpkiBase64();
  const tampered = payload.replace('r1', 'r2');
  assert.equal(verifyWithNode(tampered, signature, publicKey), false);
});

test('tampering with the signature itself invalidates verification', () => {
  const payload = JSON.stringify({ restaurantId: 'r1' });
  const signature = signOfflinePayload(payload);
  const publicKey = getPublicKeySpkiBase64();
  const tamperedSig = signature.slice(0, -4) + (signature.slice(-4) === 'AAAA' ? 'BBBB' : 'AAAA');
  assert.equal(verifyWithNode(payload, tamperedSig, publicKey), false);
});

// Regression: the signing key used to be purely ephemeral (regenerated fresh
// in memory on every process start, never written to disk) — since packaged
// builds never have OFFLINE_LICENSE_PRIVATE_KEY configured (no `.env` is
// bundled), this silently invalidated every previously-issued offline
// license's signature on every single app restart. Worse, evaluateOfflineAccess
// checks the signature BEFORE the expiration date, so a key mismatch reports
// tier 'blocked' instead of the license's real 'expired' status — and
// 'blocked' is only enforced while offline, not online — meaning an
// already-expired license could regain full access after a restart simply by
// being online at that moment. The key must now be generated once and
// persisted under DATA_DIR so it survives a restart.
test('the signing key is persisted to a file under DATA_DIR and survives a simulated process restart', async () => {
  const keyFile = path.join(config.dataDir, '.offline-license-key.json');
  assert.ok(fs.existsSync(keyFile), 'the signing key must be written to disk on first use');
  const before = JSON.parse(fs.readFileSync(keyFile, 'utf8'));

  // Force a genuinely fresh module instance (simulating a new process, where
  // the in-memory _privateKey/_publicKey cache would be empty) by re-importing
  // with a cache-busting query string, then confirm it loads the SAME
  // persisted key from disk rather than generating a new one.
  const fresh = await import(`./offlineLicenseCrypto.js?bust=${Date.now()}-${Math.random()}`);
  const payload = JSON.stringify({ restaurantId: 'restart-test' });
  const signature = fresh.signOfflinePayload(payload);
  const publicKey = fresh.getPublicKeySpkiBase64();

  assert.equal(verifyWithNode(payload, signature, publicKey), true, 'a signature from the "restarted" module instance must still verify');
  // Also confirm the same signature verifies against the ORIGINAL module's
  // exported public key — i.e. it's truly the same key, not just internally
  // self-consistent.
  assert.equal(verifyWithNode(payload, signature, getPublicKeySpkiBase64()), true, 'the persisted key must be identical across "restarts", not merely self-consistent');

  const after = JSON.parse(fs.readFileSync(keyFile, 'utf8'));
  assert.deepEqual(after, before, 'the on-disk key file must not be rewritten/regenerated by a fresh load when it already exists');
});
